package thaumcraft.client.renderers.models.gear;

import net.minecraft.client.model.ModelBiped;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.client.renderer.GlStateManager;
import net.minecraft.entity.Entity;
import net.minecraft.entity.monster.EntitySkeleton;
import net.minecraft.entity.monster.EntityZombie;
import net.minecraft.util.math.MathHelper;

public class ModelLeaderArmor
extends ModelBiped {
    ModelRenderer Helmet;
    ModelRenderer CollarF;
    ModelRenderer CollarB;
    ModelRenderer CollarR;
    ModelRenderer CollarL;
    ModelRenderer BeltR;
    ModelRenderer Mbelt;
    ModelRenderer MbeltL;
    ModelRenderer MbeltR;
    ModelRenderer BeltL;
    ModelRenderer CloakTL;
    ModelRenderer Cloak3;
    ModelRenderer CloakTR;
    ModelRenderer Cloak1;
    ModelRenderer Cloak2;
    ModelRenderer Chestplate;
    ModelRenderer ChestOrnament;
    ModelRenderer ChestClothL;
    ModelRenderer ChestClothR;
    ModelRenderer Backplate;
    ModelRenderer GauntletstrapR1;
    ModelRenderer GauntletstrapR2;
    ModelRenderer ShoulderR;
    ModelRenderer ShoulderR1;
    ModelRenderer ShoulderR2;
    ModelRenderer ShoulderR5;
    ModelRenderer ShoulderR3;
    ModelRenderer ShoulderR4;
    ModelRenderer GauntletR2;
    ModelRenderer GauntletR;
    ModelRenderer GauntletL2;
    ModelRenderer GauntletstrapL1;
    ModelRenderer GauntletstrapL2;
    ModelRenderer ShoulderL;
    ModelRenderer ShoulderL1;
    ModelRenderer ShoulderL2;
    ModelRenderer ShoulderL3;
    ModelRenderer ShoulderL5;
    ModelRenderer ShoulderL4;
    ModelRenderer GauntletL;
    ModelRenderer LegClothR;
    ModelRenderer BackpanelR2;
    ModelRenderer BackpanelR3;
    ModelRenderer BackpanelR4;
    ModelRenderer LegClothL;
    ModelRenderer BackpanelL4;
    ModelRenderer BackpanelL2;
    ModelRenderer BackpanelL3;
    ModelRenderer BackpanelL1;
    ModelRenderer BackpanelR1;

    public ModelLeaderArmor(float f) {
        super(f, 0.0f, 128, 64);
        this.textureWidth = 128;
        this.textureHeight = 64;
        this.Helmet = new ModelRenderer(this, 41, 8);
        this.Helmet.addBox(-4.5f, -9.0f, -4.5f, 9, 9, 9);
        this.Helmet.setTextureSize(128, 64);
        this.setRotation(this.Helmet, 0.0f, 0.0f, 0.0f);
        this.CollarF = new ModelRenderer(this, 17, 31);
        this.CollarF.addBox(-4.5f, -1.5f, -3.0f, 9, 4, 1);
        this.CollarF.setRotationPoint(0.0f, 0.0f, -2.5f);
        this.setRotation(this.CollarF, 0.2268928f, 0.0f, 0.0f);
        this.CollarB = new ModelRenderer(this, 17, 26);
        this.CollarB.addBox(-4.5f, -1.5f, 7.0f, 9, 4, 1);
        this.CollarB.setRotationPoint(0.0f, 0.0f, -2.5f);
        this.setRotation(this.CollarB, 0.2268928f, 0.0f, 0.0f);
        this.CollarR = new ModelRenderer(this, 17, 11);
        this.CollarR.addBox(-5.5f, -1.5f, -3.0f, 1, 4, 11);
        this.CollarR.setRotationPoint(0.0f, 0.0f, -2.5f);
        this.setRotation(this.CollarR, 0.2268928f, 0.0f, 0.0f);
        this.CollarL = new ModelRenderer(this, 17, 11);
        this.CollarL.addBox(4.5f, -1.5f, -3.0f, 1, 4, 11);
        this.CollarL.setRotationPoint(0.0f, 0.0f, -2.5f);
        this.setRotation(this.CollarL, 0.2268928f, 0.0f, 0.0f);
        this.BeltR = new ModelRenderer(this, 76, 44);
        this.BeltR.addBox(-5.0f, 4.0f, -3.0f, 1, 3, 6);
        this.BeltR.setTextureSize(128, 64);
        this.setRotation(this.BeltR, 0.0f, 0.0f, 0.0f);
        this.Mbelt = new ModelRenderer(this, 56, 55);
        this.Mbelt.addBox(-4.0f, 8.0f, -3.0f, 8, 4, 1);
        this.Mbelt.setTextureSize(128, 64);
        this.setRotation(this.Mbelt, 0.0f, 0.0f, 0.0f);
        this.MbeltL = new ModelRenderer(this, 76, 44);
        this.MbeltL.addBox(4.0f, 8.0f, -3.0f, 1, 3, 6);
        this.MbeltL.setTextureSize(128, 64);
        this.setRotation(this.MbeltL, 0.0f, 0.0f, 0.0f);
        this.MbeltR = new ModelRenderer(this, 76, 44);
        this.MbeltR.addBox(-5.0f, 8.0f, -3.0f, 1, 3, 6);
        this.MbeltR.setTextureSize(128, 64);
        this.setRotation(this.MbeltR, 0.0f, 0.0f, 0.0f);
        this.BeltL = new ModelRenderer(this, 76, 44);
        this.BeltL.addBox(4.0f, 4.0f, -3.0f, 1, 3, 6);
        this.BeltL.setTextureSize(128, 64);
        this.setRotation(this.BeltL, 0.0f, 0.0f, 0.0f);
        this.CloakTL = new ModelRenderer(this, 0, 43);
        this.CloakTL.addBox(2.5f, 1.0f, -1.0f, 2, 1, 3);
        this.CloakTL.setRotationPoint(0.0f, 0.0f, 3.0f);
        this.setRotation(this.CloakTL, 0.1396263f, 0.0f, 0.0f);
        this.Cloak3 = new ModelRenderer(this, 0, 59);
        this.Cloak3.addBox(-4.5f, 17.0f, -3.7f, 9, 4, 1);
        this.Cloak3.setRotationPoint(0.0f, 0.0f, 3.0f);
        this.setRotation(this.Cloak3, 0.4465716f, 0.0f, 0.0f);
        this.CloakTR = new ModelRenderer(this, 0, 43);
        this.CloakTR.addBox(-4.5f, 1.0f, -1.0f, 2, 1, 3);
        this.CloakTR.setRotationPoint(0.0f, 0.0f, 3.0f);
        this.setRotation(this.CloakTR, 0.1396263f, 0.0f, 0.0f);
        this.Cloak1 = new ModelRenderer(this, 0, 47);
        this.Cloak1.addBox(-4.5f, 2.0f, 1.0f, 9, 12, 1);
        this.Cloak1.setRotationPoint(0.0f, 0.0f, 3.0f);
        this.setRotation(this.Cloak1, 0.1396263f, 0.0f, 0.0f);
        this.Cloak2 = new ModelRenderer(this, 0, 59);
        this.Cloak2.addBox(-4.5f, 14.0f, -1.3f, 9, 4, 1);
        this.Cloak2.setRotationPoint(0.0f, 0.0f, 3.0f);
        this.setRotation(this.Cloak2, 0.3069452f, 0.0f, 0.0f);
        this.Chestplate = new ModelRenderer(this, 56, 45);
        this.Chestplate.addBox(-4.0f, 1.0f, -3.8f, 8, 7, 2);
        this.Chestplate.setTextureSize(128, 64);
        this.setRotation(this.Chestplate, 0.0f, 0.0f, 0.0f);
        this.ChestOrnament = new ModelRenderer(this, 76, 53);
        this.ChestOrnament.addBox(-2.5f, 3.0f, -4.8f, 5, 5, 1);
        this.ChestOrnament.setTextureSize(128, 64);
        this.setRotation(this.ChestOrnament, 0.0f, 0.0f, 0.0f);
        this.ChestClothL = new ModelRenderer(this, 20, 47);
        this.ChestClothL.mirror = true;
        this.ChestClothL.addBox(1.5f, 1.2f, -4.5f, 3, 9, 1);
        this.ChestClothL.setTextureSize(128, 64);
        this.setRotation(this.ChestClothL, 0.0663225f, 0.0f, 0.0f);
        this.ChestClothR = new ModelRenderer(this, 20, 47);
        this.ChestClothR.addBox(-4.5f, 1.2f, -4.5f, 3, 9, 1);
        this.ChestClothR.setTextureSize(128, 64);
        this.setRotation(this.ChestClothR, 0.0663225f, 0.0f, 0.0f);
        this.Backplate = new ModelRenderer(this, 36, 45);
        this.Backplate.addBox(-4.0f, 1.0f, 2.0f, 8, 11, 2);
        this.Backplate.setTextureSize(128, 64);
        this.setRotation(this.Backplate, 0.0f, 0.0f, 0.0f);
        this.GauntletR = new ModelRenderer(this, 100, 26);
        this.GauntletR.addBox(-3.5f, 3.5f, -2.5f, 2, 6, 5);
        this.GauntletR.setTextureSize(128, 64);
        this.setRotation(this.GauntletR, 0.0f, 0.0f, 0.0f);
        this.GauntletL = new ModelRenderer(this, 114, 26);
        this.GauntletL.addBox(1.5f, 3.5f, -2.5f, 2, 6, 5);
        this.GauntletL.setTextureSize(128, 64);
        this.setRotation(this.GauntletL, 0.0f, 0.0f, 0.0f);
        this.GauntletstrapL1 = new ModelRenderer(this, 84, 31);
        this.GauntletstrapL1.mirror = true;
        this.GauntletstrapL1.addBox(-1.5f, 3.5f, -2.5f, 3, 1, 5);
        this.GauntletstrapL1.setTextureSize(128, 64);
        this.setRotation(this.GauntletstrapL1, 0.0f, 0.0f, 0.0f);
        this.GauntletstrapL2 = new ModelRenderer(this, 84, 31);
        this.GauntletstrapL2.mirror = true;
        this.GauntletstrapL2.addBox(-1.5f, 6.5f, -2.5f, 3, 1, 5);
        this.GauntletstrapL2.setTextureSize(128, 64);
        this.setRotation(this.GauntletstrapL2, 0.0f, 0.0f, 0.0f);
        this.GauntletstrapR1 = new ModelRenderer(this, 84, 31);
        this.GauntletstrapR1.addBox(-1.5f, 3.5f, -2.5f, 3, 1, 5);
        this.GauntletstrapR1.setTextureSize(128, 64);
        this.setRotation(this.GauntletstrapR1, 0.0f, 0.0f, 0.0f);
        this.GauntletstrapR2 = new ModelRenderer(this, 84, 31);
        this.GauntletstrapR2.addBox(-1.5f, 6.5f, -2.5f, 3, 1, 5);
        this.GauntletstrapR2.setTextureSize(128, 64);
        this.setRotation(this.GauntletstrapR2, 0.0f, 0.0f, 0.0f);
        this.GauntletR2 = new ModelRenderer(this, 102, 37);
        this.GauntletR2.addBox(-5.0f, 3.5f, -2.0f, 1, 5, 4);
        this.GauntletR2.setTextureSize(128, 64);
        this.setRotation(this.GauntletR2, 0.0f, 0.0f, -0.1675516f);
        this.GauntletL2 = new ModelRenderer(this, 102, 37);
        this.GauntletL2.addBox(4.0f, 3.5f, -2.0f, 1, 5, 4);
        this.GauntletL2.setTextureSize(128, 64);
        this.setRotation(this.GauntletL2, 0.0f, 0.0f, 0.1675516f);
        this.ShoulderR = new ModelRenderer(this, 56, 35);
        this.ShoulderR.addBox(-3.5f, -2.5f, -2.5f, 5, 5, 5);
        this.ShoulderR.setTextureSize(128, 64);
        this.setRotation(this.ShoulderR, 0.0f, 0.0f, 0.0f);
        this.ShoulderR1 = new ModelRenderer(this, 0, 0);
        this.ShoulderR1.addBox(-4.3f, -1.5f, -3.0f, 3, 5, 6);
        this.ShoulderR1.setTextureSize(128, 64);
        this.setRotation(this.ShoulderR1, 0.0f, 0.0f, 0.7853982f);
        this.ShoulderR2 = new ModelRenderer(this, 0, 19);
        this.ShoulderR2.addBox(-3.3f, 3.5f, -2.5f, 1, 1, 5);
        this.ShoulderR2.setTextureSize(128, 64);
        this.setRotation(this.ShoulderR2, 0.0f, 0.0f, 0.7853982f);
        this.ShoulderR5 = new ModelRenderer(this, 18, 4);
        this.ShoulderR5.addBox(-2.3f, -1.5f, 3.0f, 1, 6, 1);
        this.ShoulderR5.setTextureSize(128, 64);
        this.setRotation(this.ShoulderR5, 0.0f, 0.0f, 0.7853982f);
        this.ShoulderR3 = new ModelRenderer(this, 0, 11);
        this.ShoulderR3.addBox(-2.3f, 3.5f, -3.0f, 1, 2, 6);
        this.ShoulderR3.setTextureSize(128, 64);
        this.setRotation(this.ShoulderR3, 0.0f, 0.0f, 0.7853982f);
        this.ShoulderR4 = new ModelRenderer(this, 18, 4);
        this.ShoulderR4.addBox(-2.3f, -1.5f, -4.0f, 1, 6, 1);
        this.ShoulderR4.setTextureSize(128, 64);
        this.setRotation(this.ShoulderR4, 0.0f, 0.0f, 0.7853982f);
        this.ShoulderL = new ModelRenderer(this, 56, 35);
        this.ShoulderL.addBox(-1.5f, -2.5f, -2.5f, 5, 5, 5);
        this.ShoulderL.setTextureSize(128, 64);
        this.setRotation(this.ShoulderL, 0.0f, 0.0f, 0.0f);
        this.ShoulderL1 = new ModelRenderer(this, 0, 0);
        this.ShoulderL1.addBox(1.3f, -1.5f, -3.0f, 3, 5, 6);
        this.ShoulderL1.setTextureSize(128, 64);
        this.setRotation(this.ShoulderL1, 0.0f, 0.0f, -0.7853982f);
        this.ShoulderL2 = new ModelRenderer(this, 0, 19);
        this.ShoulderL2.mirror = true;
        this.ShoulderL2.addBox(2.3f, 3.5f, -2.5f, 1, 1, 5);
        this.ShoulderL2.setTextureSize(128, 64);
        this.setRotation(this.ShoulderL2, 0.0f, 0.0f, -0.7853982f);
        this.ShoulderL3 = new ModelRenderer(this, 0, 11);
        this.ShoulderL3.addBox(1.3f, 3.5f, -3.0f, 1, 2, 6);
        this.ShoulderL3.setTextureSize(128, 64);
        this.setRotation(this.ShoulderL3, 0.0f, 0.0f, -0.7853982f);
        this.ShoulderL5 = new ModelRenderer(this, 18, 4);
        this.ShoulderL5.addBox(1.3f, -1.5f, 3.0f, 1, 6, 1);
        this.ShoulderL5.setTextureSize(128, 64);
        this.setRotation(this.ShoulderL5, 0.0f, 0.0f, -0.7853982f);
        this.ShoulderL4 = new ModelRenderer(this, 18, 4);
        this.ShoulderL4.addBox(1.3f, -1.5f, -4.0f, 1, 6, 1);
        this.ShoulderL4.setTextureSize(128, 64);
        this.setRotation(this.ShoulderL4, 0.0f, 0.0f, -0.7853982f);
        this.LegClothR = new ModelRenderer(this, 20, 55);
        this.LegClothR.addBox(0.0f, 0.0f, 0.0f, 3, 8, 1);
        this.LegClothR.setRotationPoint(-4.5f, 10.4f, -3.9f);
        this.LegClothR.setTextureSize(128, 64);
        this.setRotation(this.LegClothR, -0.0349066f, 0.0f, 0.0f);
        this.LegClothL = new ModelRenderer(this, 20, 55);
        this.LegClothL.mirror = true;
        this.LegClothL.addBox(0.0f, 0.0f, 0.0f, 3, 8, 1);
        this.LegClothL.setRotationPoint(1.5f, 10.4f, -3.9f);
        this.LegClothL.setTextureSize(128, 64);
        this.setRotation(this.LegClothL, -0.0349066f, 0.0f, 0.0f);
        this.BackpanelR1 = new ModelRenderer(this, 0, 25);
        this.BackpanelR1.addBox(-3.0f, -0.5f, 2.5f, 5, 7, 1);
        this.BackpanelR1.setTextureSize(128, 64);
        this.setRotation(this.BackpanelR1, 0.0698132f, 0.0f, 0.0f);
        this.BackpanelR2 = new ModelRenderer(this, 96, 14);
        this.BackpanelR2.addBox(-3.0f, -0.5f, -2.5f, 5, 3, 5);
        this.BackpanelR2.setTextureSize(128, 64);
        this.setRotation(this.BackpanelR2, 0.0f, 0.0f, 0.1396263f);
        this.BackpanelR3 = new ModelRenderer(this, 116, 13);
        this.BackpanelR3.addBox(-3.0f, 2.5f, -2.5f, 1, 4, 5);
        this.BackpanelR3.setTextureSize(128, 64);
        this.setRotation(this.BackpanelR3, 0.0f, 0.0f, 0.1396263f);
        this.BackpanelR4 = new ModelRenderer(this, 0, 25);
        this.BackpanelR4.mirror = true;
        this.BackpanelR4.addBox(-3.0f, -0.5f, -3.5f, 5, 7, 1);
        this.BackpanelR4.setTextureSize(128, 64);
        this.setRotation(this.BackpanelR4, -0.0349066f, 0.0f, 0.0f);
        this.BackpanelL1 = new ModelRenderer(this, 0, 25);
        this.BackpanelL1.addBox(-2.0f, -0.5f, 2.5f, 5, 7, 1);
        this.BackpanelL1.setTextureSize(128, 64);
        this.setRotation(this.BackpanelL1, 0.0698132f, 0.0f, 0.0f);
        this.BackpanelL4 = new ModelRenderer(this, 0, 25);
        this.BackpanelL4.addBox(-2.0f, -0.5f, -3.5f, 5, 7, 1);
        this.BackpanelL4.setTextureSize(128, 64);
        this.setRotation(this.BackpanelL4, -0.0349066f, 0.0f, 0.0f);
        this.BackpanelL2 = new ModelRenderer(this, 96, 14);
        this.BackpanelL2.addBox(-2.0f, -0.5f, -2.5f, 5, 3, 5);
        this.BackpanelL2.setTextureSize(128, 64);
        this.setRotation(this.BackpanelL2, 0.0f, 0.0f, -0.1396263f);
        this.BackpanelL3 = new ModelRenderer(this, 116, 13);
        this.BackpanelL3.addBox(2.0f, 2.5f, -2.5f, 1, 4, 5);
        this.BackpanelL3.setTextureSize(128, 64);
        this.setRotation(this.BackpanelL3, 0.0f, 0.0f, -0.1396263f);
        this.bipedHeadwear.cubeList.clear();
        this.bipedHead.cubeList.clear();
        this.bipedHead.addChild(this.Helmet);
        this.bipedBody.cubeList.clear();
        this.bipedRightLeg.cubeList.clear();
        this.bipedLeftLeg.cubeList.clear();
        this.bipedBody.addChild(this.Mbelt);
        this.bipedBody.addChild(this.MbeltL);
        this.bipedBody.addChild(this.MbeltR);
        if (!(f < 1.0f)) {
            this.bipedBody.addChild(this.BeltL);
            this.bipedBody.addChild(this.BeltR);
            this.bipedBody.addChild(this.Chestplate);
            this.bipedBody.addChild(this.ChestOrnament);
            this.bipedBody.addChild(this.ChestClothR);
            this.bipedBody.addChild(this.ChestClothL);
            this.bipedBody.addChild(this.LegClothR);
            this.bipedBody.addChild(this.LegClothL);
            this.bipedBody.addChild(this.Backplate);
            this.bipedBody.addChild(this.CollarB);
            this.bipedBody.addChild(this.CollarR);
            this.bipedBody.addChild(this.CollarL);
            this.bipedBody.addChild(this.CollarF);
            this.bipedBody.addChild(this.Cloak1);
            this.bipedBody.addChild(this.Cloak2);
            this.bipedBody.addChild(this.Cloak3);
            this.bipedBody.addChild(this.CloakTL);
            this.bipedBody.addChild(this.CloakTR);
        }
        this.bipedRightArm.cubeList.clear();
        this.bipedRightArm.addChild(this.ShoulderR);
        this.bipedRightArm.addChild(this.ShoulderR1);
        this.bipedRightArm.addChild(this.ShoulderR2);
        this.bipedRightArm.addChild(this.ShoulderR3);
        this.bipedRightArm.addChild(this.ShoulderR4);
        this.bipedRightArm.addChild(this.ShoulderR5);
        this.bipedRightArm.addChild(this.GauntletR);
        this.bipedRightArm.addChild(this.GauntletR2);
        this.bipedRightArm.addChild(this.GauntletstrapR1);
        this.bipedRightArm.addChild(this.GauntletstrapR2);
        this.bipedLeftArm.cubeList.clear();
        this.bipedLeftArm.addChild(this.ShoulderL);
        this.bipedLeftArm.addChild(this.ShoulderL1);
        this.bipedLeftArm.addChild(this.ShoulderL2);
        this.bipedLeftArm.addChild(this.ShoulderL3);
        this.bipedLeftArm.addChild(this.ShoulderL4);
        this.bipedLeftArm.addChild(this.ShoulderL5);
        this.bipedLeftArm.addChild(this.GauntletL);
        this.bipedLeftArm.addChild(this.GauntletL2);
        this.bipedLeftArm.addChild(this.GauntletstrapL1);
        this.bipedLeftArm.addChild(this.GauntletstrapL2);
        this.bipedRightLeg.addChild(this.BackpanelR1);
        this.bipedRightLeg.addChild(this.BackpanelR2);
        this.bipedRightLeg.addChild(this.BackpanelR3);
        this.bipedRightLeg.addChild(this.BackpanelR4);
        this.bipedLeftLeg.addChild(this.BackpanelL1);
        this.bipedLeftLeg.addChild(this.BackpanelL2);
        this.bipedLeftLeg.addChild(this.BackpanelL3);
        this.bipedLeftLeg.addChild(this.BackpanelL4);
    }

    @Override
    public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5) {
        if (entity instanceof EntitySkeleton || entity instanceof EntityZombie) {
            this.setRotationAnglesZombie(f, f1, f2, f3, f4, f5, entity);
        } else {
            this.setRotationAngles(f, f1, f2, f3, f4, f5, entity);
        }
        float a = MathHelper.cos(f * 0.6662f) * 1.4f * f1;
        float b = MathHelper.cos(f * 0.6662f + (float)Math.PI) * 1.4f * f1;
        float c = Math.min(a, b);
        this.LegClothR.rotateAngleX = a - 0.1047198f;
        this.LegClothL.rotateAngleX = b - 0.1047198f;
        this.Cloak1.rotateAngleX = -c / 2.0f + 0.1396263f;
        this.Cloak2.rotateAngleX = -c / 2.0f + 0.3069452f;
        this.Cloak3.rotateAngleX = -c / 2.0f + 0.4465716f;
        if (this.isChild) {
            float f6 = 2.0f;
            GlStateManager.pushMatrix();
            GlStateManager.scale(1.5f / f6, 1.5f / f6, 1.5f / f6);
            GlStateManager.translate(0.0f, 16.0f * f5, 0.0f);
            this.bipedHead.render(f5);
            GlStateManager.popMatrix();
            GlStateManager.pushMatrix();
            GlStateManager.scale(1.0f / f6, 1.0f / f6, 1.0f / f6);
            GlStateManager.translate(0.0f, 24.0f * f5, 0.0f);
            this.bipedBody.render(f5);
            this.bipedRightArm.render(f5);
            this.bipedLeftArm.render(f5);
            this.bipedRightLeg.render(f5);
            this.bipedLeftLeg.render(f5);
            this.bipedHeadwear.render(f5);
            GlStateManager.popMatrix();
        } else {
            GlStateManager.pushMatrix();
            GlStateManager.scale(1.01f, 1.01f, 1.01f);
            this.bipedHead.render(f5);
            GlStateManager.popMatrix();
            this.bipedBody.render(f5);
            this.bipedRightArm.render(f5);
            this.bipedLeftArm.render(f5);
            this.bipedRightLeg.render(f5);
            this.bipedLeftLeg.render(f5);
            this.bipedHeadwear.render(f5);
        }
    }

    private void setRotation(ModelRenderer model, float x, float y, float z) {
        model.rotateAngleX = x;
        model.rotateAngleY = y;
        model.rotateAngleZ = z;
    }

    public void setRotationAnglesZombie(float p_78087_1_, float p_78087_2_, float p_78087_3_, float p_78087_4_, float p_78087_5_, float p_78087_6_, Entity p_78087_7_) {
        super.setRotationAngles(p_78087_1_, p_78087_2_, p_78087_3_, p_78087_4_, p_78087_5_, p_78087_6_, p_78087_7_);
        float f6 = MathHelper.sin(this.swingProgress * (float)Math.PI);
        float f7 = MathHelper.sin((1.0f - (1.0f - this.swingProgress) * (1.0f - this.swingProgress)) * (float)Math.PI);
        this.bipedRightArm.rotateAngleZ = 0.0f;
        this.bipedLeftArm.rotateAngleZ = 0.0f;
        this.bipedRightArm.rotateAngleY = -(0.1f - f6 * 0.6f);
        this.bipedLeftArm.rotateAngleY = 0.1f - f6 * 0.6f;
        this.bipedRightArm.rotateAngleX = -1.5707964f;
        this.bipedLeftArm.rotateAngleX = -1.5707964f;
        this.bipedRightArm.rotateAngleX -= f6 * 1.2f - f7 * 0.4f;
        this.bipedLeftArm.rotateAngleX -= f6 * 1.2f - f7 * 0.4f;
        this.bipedRightArm.rotateAngleZ += MathHelper.cos(p_78087_3_ * 0.09f) * 0.05f + 0.05f;
        this.bipedLeftArm.rotateAngleZ -= MathHelper.cos(p_78087_3_ * 0.09f) * 0.05f + 0.05f;
        this.bipedRightArm.rotateAngleX += MathHelper.sin(p_78087_3_ * 0.067f) * 0.05f;
        this.bipedLeftArm.rotateAngleX -= MathHelper.sin(p_78087_3_ * 0.067f) * 0.05f;
    }
}
